[package]
name = "birthday_paradox_sim"
version = "0.1.0"
authors = ["Immortalin <immortalin@outlook.com>"]
edition = "2018"

[dependencies]
rand = "0.6"
getopts = "0.2"
rayon = "1.0"
plotlib = "0.4.0"